server:
  port: 8010

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:7777/realms/sfo
            user-name-attribute: preferred_username
            

        registration:
          keycloak:
            client-id: sfo
            authorization-grant-type: authorization_code
            scope: openid

  mustache:
    check-template-location: false
  datasource:
    url: jdbc:postgresql://localhost:5432/sfo
    driver-class-name: org.postgresql.Driver
    username: sfo
    password: sfo
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: false

vaadin:
  whitelisted-packages:
    - com.vaadin
    - org.vaadin
    - dev.hilla
    - de.htb.sfo
application:
  navigation:
    name:
      home: "Home"
      teams: "Mannschaften"
      occupancy: "Belegung"
      fields: "Sportplätze"

logging:
  org:
    atmosphere: DEBUG
